#!/usr/bin/env python3
"""Generate the static GitHub Pages artifact."""

from __future__ import annotations

import argparse
import json
import re
from datetime import datetime, timezone, timedelta
from pathlib import Path


UPDATE_TIME_RE = re.compile(
    r"数据更新时间：\d{4}年\d{1,2}月\d{1,2}日 \| 数据来源：各平台公开榜单"
)
BASE_SONGS_RE = re.compile(
    r"const baseSongs = \[\s*(.*?)\s*\];",
    re.DOTALL,
)


def china_today() -> datetime:
    return datetime.now(timezone(timedelta(hours=8)))


def load_songs(path: Path) -> list[dict]:
    if not path.exists():
        return []
    payload = json.loads(path.read_text(encoding="utf-8"))
    songs = payload.get("songs", [])
    if not isinstance(songs, list):
        raise ValueError(f"{path} does not contain a songs list")
    return songs


def js_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def render_song(song: dict) -> str:
    platforms = song.get("platforms") or []
    if not isinstance(platforms, list):
        platforms = []
    platform_js = ", ".join(js_string(str(platform)) for platform in platforms)

    fields = [
        f"rank: {int(song['rank'])}",
        f"title: {js_string(str(song['title']))}",
        f"artist: {js_string(str(song['artist']))}",
        f"platforms: [{platform_js}]",
        f"plays: {int(song.get('plays', 0))}",
        f"daysOnChart: {int(song.get('daysOnChart', 7))}",
        f"peakRank: {int(song.get('peakRank', song['rank']))}",
    ]
    if song.get("isNew"):
        fields.insert(5, "isNew: true")
    return "            { " + ", ".join(fields) + " }"


def replace_base_songs(html: str, songs: list[dict]) -> str:
    if not songs:
        return html

    rendered = ",\n".join(render_song(song) for song in songs)
    replacement = (
        "const baseSongs = [\n"
        "            // Generated from live chart sources by scripts/fetch_charts.py\n"
        f"{rendered}\n"
        "        ];"
    )
    html, replacements = BASE_SONGS_RE.subn(replacement, html, count=1)
    if replacements != 1:
        raise ValueError("Could not replace the baseSongs array in index.html")
    return html


def render_page(
    source: Path,
    output_dir: Path,
    data_file: Path,
    now: datetime | None = None,
) -> Path:
    html = source.read_text(encoding="utf-8")
    current = now or china_today()
    update_text = (
        f"数据更新时间：{current.year}年{current.month}月{current.day}日 | "
        "数据来源：各平台公开榜单"
    )

    html, replacements = UPDATE_TIME_RE.subn(update_text, html, count=1)
    if replacements != 1:
        raise ValueError("Could not update the page timestamp in index.html")

    html = replace_base_songs(html, load_songs(data_file))

    output_dir.mkdir(parents=True, exist_ok=True)
    output_path = output_dir / "index.html"
    output_path.write_text(html, encoding="utf-8")
    (output_dir / ".nojekyll").write_text("", encoding="utf-8")
    return output_path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--source",
        type=Path,
        default=Path("index.html"),
        help="Source HTML file to render.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("_site"),
        help="Directory for the generated GitHub Pages artifact.",
    )
    parser.add_argument(
        "--data-file",
        type=Path,
        default=Path("data/songs.json"),
        help="Normalized chart data generated by scripts/fetch_charts.py.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    output_path = render_page(args.source, args.output_dir, args.data_file)
    print(f"Generated {output_path}")


if __name__ == "__main__":
    main()
